name: Flutter CI/CD

on:
  push:
    branches: [main]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: stable

      - name: Install dependencies
        run: flutter pub get
        working-directory: dueltap

      - name: Run analyzer
        run: flutter analyze
        working-directory: dueltap

      - name: Run tests
        run: flutter test
        working-directory: dueltap

      - name: Build Android APK (release)
        run: flutter build apk --release
        working-directory: dueltap

      - name: Build iOS (release, no-codesign)
        run: flutter build ios --release --no-codesign
        working-directory: dueltap

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: dueltap/build/app/outputs/flutter-apk/app-release.apk

      - name: Upload iOS build
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: dueltap/build/ios/iphoneos/Runner.app
